---
- name: Remove k3s Group
  group:
    name: "{{ k3s.os_user.group }}"
    gid: "{{ k3s.os_user.gid }}"
    state: absent
  become: yes

- name: Remove k3s User
  user:
    name: "{{ k3s.os_user.user }}"
    uid: "{{ k3s.os_user.uid }}"
    state: absent
  become: yes

- name: Remove home-directory of user k3s
  file:
    path: "/home/{{ k3s.os_user.user }}"
    state: absent
  become: yes
